### ISSUE TITLE
Nothing is serving git repositories

### ISSUE THREAD

**Issue by gabriel-samfira** [cloudbase/zuul-charm#3]
Please see:

http://docs.openstack.org/infra/zuul/merger.html

Zuul does not make repositories available for consumption. Apache/web server is needed.

**Comment by ionutbalutoiu** [comment]
Apache2 was added in [this](https://github.com/cloudbase/zuul-charm/commit/050b03ad0ea5f1e04e3fb80a33ee9a516e3c8c0d) commit to serve git repositories.
